
project_id = "vahtrfkpnffcjuvhuwgm"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[[publications]]
name = "supabase_realtime"
publication_id = "supabase_realtime"
tables = []

[realtime]
enabled = true
hostname = "localhost"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_expiry = 2592000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[storage]
enabled = true
file_size_limit = "50MiB"

[analytics]
enabled = false
port = 54324

[functions]
[functions.deepseek]
verify_jwt = false
env_DEEPSEEK_API_KEY = "sk-c41441aa0398496691ab4276756da8cb"

[functions.send-welcome-email]
verify_jwt = false
env_SITE_URL = "https://lovable.dev"

[inbucket]
enabled = true
port = 54324

